# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c97258b2792eface00aa1d053fcc22cc8dcc42fcc0468a684e41d1b0b3ac26bfe9f9ebb5796ec6fa5d92f94d64d33593f96be3fe7eed2b17ba0f135a04c67de0

test:
  secret_key_base: 6c8e88302d4d0adc897bdb0964dbc9663b10efafcf34e50253331520b82a218a8077e15b10bdaee0c2dedc0d4222aad277a99867cab6027563aed088bb0b4214

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
